---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-greeter
          image: greeter:final
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: greeter-service
spec:
  selector:
    app: hello-app
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

